Use withenoise to manage the static files
fedora-infra/fpdc pull request #29
Opened 2018-09-27 13:43 UTC by cverna

Signed-off-by: Clement Verna <cverna@tutanota.com>

2018-09-27 16:23 UTC, subpop requested changes

2018-09-27 16:23 UTC, subpop commented on fpdc/settings/prod.py
> +MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")  # NOQA
Does appending the middleware component here place it above all other middleware components, as [the quickstart suggests](http://whitenoise.evans.io/en/stable/#quickstart-for-django-apps)? I know middleware ordering is very particular.

2018-09-27 16:27 UTC, cverna commented on fpdc/settings/prod.py
> +MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")  # NOQA
Yeah good point, I might just add it to the base.py file directly.

2018-09-29 04:59 UTC, subpop commented
Cool, LGTM.

2018-09-29 05:00 UTC, subpop approved these changes

2018-09-29 12:25 UTC, merged